alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias install="sudo apt-get install"
alias search="sudo apt-cache search"
alias list="apt list --installed"
alias autoremove="sudo apt autoremove"
alias targz="tar -xvf"
alias off="sudo shutdown -h now"
alias reboot="sudo reboot"
# git alias
alias clone="git clone"
alias pull="git pull"
alias push="git push"
alias fetch="git fetch"
alias status="git status"
alias add="git add --all"
alias commit="git commit -m"
alias checkout="git checkout"
alias log="git log --graph"
alias branch="git branch -a"

# linux command
alias la="ls -ah"
alias ll="ls -lh"